### ISSUE TITLE
"refit: True" not working

### ISSUE THREAD

**Issue by zachbarfield60** [ergodicio/inverse-thomson-scattering#48]
Toggling on "refit" is not working.
When running with 
```
other:
    refit: True
```
I receive the following error after the code finishes its first pass:
```
`Traceback (most recent call last):
  File "/global/u2/z/zachb/inverse-thomson-scattering/run_tsadar.py", line 21, in <module>
    run_job(args.run_id, nested=None)
  File "/global/u2/z/zachb/inverse-thomson-scattering/inverse_thomson_scattering/runner.py", line 128, in run_job
    _run_(config, mode="fit")
  File "/global/u2/z/zachb/inverse-thomson-scattering/inverse_thomson_scattering/runner.py", line 97, in _run_
    fit_results, loss = fitter.fit(config=config)
  File "/global/u2/z/zachb/inverse-thomson-scattering/inverse_thomson_scattering/fitter.py", line 409, in fit
    final_params = postprocess.postprocess(config, batch_indices, all_data, all_axes, ts_fitter, sa, fitted_weights)
  File "/global/u2/z/zachb/inverse-thomson-scattering/inverse_thomson_scattering/process/postprocess.py", line 194, in postprocess
    new_weights = np.zeros(ts_fitter_refit["init_weights"].shape)
TypeError: 'TSFitter' object is not subscriptable
srun: error: nid002917: task 0: Exited with exit code 1
srun: Terminating StepId=20514285.0`
```

**Comment by joglekara** [comment]
Yes I definitely broke the refitter

**Comment by almilder** [comment]
The updated main branch includes a fix for refitting
